[versions]
kotlin = "1.8.0"
coroutines = "1.6.4"
moshi = "1.14.0"
spotless = "6.3.0"
kotlinxHtml = "0.7.5"
kotlinxCli = "0.3.5"
mavenPublish = "0.24.0"
androidGradlePlugin = "7.3.1"
gradlePluginPublish = "1.1.0"

[libraries]
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-html-jvm = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinxHtml" }
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinxCli" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }